export const config = {
  developer: {
    name: "Balla Manish Ranganatha Chowdary",
    title: "AI Full Stack Developer",
    bio: "AI Full Stack Developer creating digital experiences that respect humans and scale with clarity. Accessibility is my north star.",
    avatar: "/profile-pic.png",
  },
  social: {
    github: "Balla-Manish-Ranganatha-Chowdary",
    email: "manishballa00@gmail.com",
    location: "Banglore",
  },
  projects: [
    {
      id: 1,
      title: "Differentiated Caseflow Management",
      description: "A comprehensive case management system designed to streamline legal workflows, track case progress, and manage documentation efficiently with role-based access control.",
      image: "/projects/project-1.webp",
      technologies: ["React.js", "FastAPI", "MySQL"],
      github: "https://github.com/Balla-Manish-Ranganatha-Chowdary/Differentiated-Caseflow-Management",
      demo: "#",
    },
    {
      id: 2,
      title: "Double Blind Token System",
      description: "Eliminating corruption in government services through technology and transparency. A production-ready, open-source platform that revolutionizes government service delivery by ensuring complete anonymity between citizens and officers. Built to prevent bribery and corruption through innovative double-blind encryption and AI-powered automation.",
      image: "/projects/project-2.webp",
      technologies: ["Next.js", "Django REST Framework", "PostgreSQL"],
      github: "https://github.com/Balla-Manish-Ranganatha-Chowdary/Double-Blind-Token-System",
      demo: "#",
    },
    {
      id: 3,
      title: "Generative UI for Accessibility",
      description: "An AI-powered system that generates accessible user interfaces dynamically, ensuring WCAG compliance and improving web accessibility for users with disabilities.",
      image: "/projects/project-3.webp",
      technologies: ["React.js", "RAG using Llama"],
      github: "https://github.com/Balla-Manish-Ranganatha-Chowdary/Generative-UI-for-Accessibility",
      demo: "#",
    },
    {
      id: 4,
      title: "Job Recommendation System",
      description: "An intelligent job matching platform using machine learning algorithms to recommend personalized job opportunities based on skills, experience, and preferences.",
      image: "/projects/project-4.webp",
      technologies: ["Python", "Machine Learning", "React", "Scikit-learn"],
      github: "https://github.com/Balla-Manish-Ranganatha-Chowdary/Job-Recommendation-System",
      demo: "#",
    },
  ],
  skills: [
    { name: "React.js", icon: "react" },
    { name: "Next.js", icon: "nextjs" },
    { name: "JavaScript", icon: "javascript" },
    { name: "Tailwind CSS", icon: "tailwind" },
    { name: "MySQL", icon: "mysql" },
    { name: "PostgreSQL", icon: "postgresql" },
    { name: "Python", icon: "python" },
    { name: "FastAPI", icon: "fastapi" },
    { name: "Django REST Framework", icon: "django" },
    { name: "TensorFlow", icon: "tensorflow" },
    { name: "PyTorch", icon: "pytorch" },
    { name: "REST API", icon: "api" },
    { name: "AWS", icon: "aws" },
    { name: "Docker", icon: "docker" },
    { name: "Git", icon: "git" },
  ],
};

